framework:
  cache:
    app: cache.adapter.redis
    system: cache.adapter.redis
    default_redis_provider: 'redis://%env(string:REDIS_HOST)%:%env(string:REDIS_PORT)%'
    pools:
      doctrine.result_cache_pool:
        adapter: cache.app
      doctrine.system_cache_pool:
        adapter: cache.system
