nelmio_api_doc:
    documentation:
        info:
            title: HamTajrobe
            description: This is an awesome app to share experiences!
            version: 1.0.0
    areas: # to filter documented areas
        default:
            path_patterns:
                - ^/api/v1/auth/register # Accepts routes under /api except /api/doc
        services:
            path_patterns:
                - ^/api(?!/(doc|v1\/auth\/refresh)$) # Accepts routes under /api except /api/doc
