nelmio_api_doc:
  documentation:
    openapi: 3.0.0
    info:
      title: Ham  Tajrobe
      version: '1'
      description: A place to share awesome experiences
    components:
      securitySchemes:
        jwt:
          type: apiKey
          name: jwt
          in: header
          description: JWT authentivcation token
    security:
    - jwt: []
    tags:
    - name: Auth
      description: End-points to autenticate user and provide refresh token.
    - name: Admin
      description: End-points which are accessible just to the admin user.
    paths:
      /api/v1/auth/login:
        post:
          tags:
          - Auth
          summary: Login end-point
          security: []
          description: 'Login a user by the given credentials. It returns a `token`
            and a `refresh_token`.

            '
          requestBody:
            required: true
            content:
              application/json:
                schema:
                  type: object
                  required:
                  - phoneNumber
                  - password
                  properties:
                    phoneNumber:
                      type: string
                      description: Phone number is the unique dentifier of the use.
                    password:
                      type: string
                      description: User's password.
                    role:
                      type: string
                      description: The role to be logged in with.
                  example:
                    phoneNumber: '9121234567'
                    password: pass_1234
                    role: role_experiencer
          responses:
            '200':
              description: User authenticated successfuly.
              content:
                application/json:
                  schema:
                    type: object
                    properties:
                      status:
                        type: string
                        description: Result of the action
                      data:
                        type: object
                        description: Date payload returned from the server.
                        properties:
                          id:
                            type: integer
                            description: Id of the created user.
                          token:
                            type: string
                            description: JWT to be used while working with application.
                          refresh_token:
                            type: string
                            description: The refresh token to get new JWT if it expired.
                      message:
                        type: string
                        description: A message describing result of the action.
                    example:
                      status: success
                      data:
                        id: 1
                        token: a jwt token
                        refresh_token: a refresh token
                      message: User authenticated successfully.
            '400':
              description: A required parameter is missing or a variable format is
                wrong.
              content:
                application/json:
                  schema:
                    type: object
                    properties:
                      status:
                        type: string
                        description: Result of the action
                      message:
                        type: string
                        description: A message describing result of the action.
                    example:
                      status: failed
                      message: The key "password" is required.
            '401':
              description: User provided invalid credentials.
              content:
                application/json:
                  schema:
                    type: object
                    properties:
                      status:
                        type: string
                        description: Result of the action
                      message:
                        type: string
                        description: A message describing result of the action.
                    example:
                      status: failed
                      message: Invalid Credentials.
      /api/v1/orders/{order_id}/checkout:
        get:
          tags:
          - Orders
          summary: Order checkout
          security:
          - jwt: []
          description: 'If the order is purchasable redirect experiencer to bank page.

            '
          parameters:
          - name: order-id
            required: true
            in: path
            description: 'The id of the order to be purchased.

              '
            schema:
              type: integer
          responses:
            '303':
              description: Experiencer is redirected to bank page.
            '400':
              description: The user is trying to purchase a wrong order
              content:
                application/json:
                  schema:
                    type: object
                    properties:
                      status:
                        type: string
                        description: Result of the action.
                      message:
                        type: string
                        description: Description about what happened.
                    example:
                      status: failed
                      messaage: The order id(order-id) is not purchasable.
      /api/v1/admin/categories:
        post:
          tags:
          - Admin
          summary: Admin create a new category
          security:
          - jwt: []
          description: 'Using this end point admin creates a new category.

            '
          requestBody:
            required: true
            content:
              application/json:
                schema:
                  type: object
                  required:
                  - name
                  properties:
                    name:
                      type: string
                      description: Name of the new category
                  example:
                    name: Skydiving
          responses:
            '200':
              description: Admin created a new category
              content:
                application/json:
                  schema:
                    type: object
                    properties:
                      status:
                        type: string
                        description: Result of the action
                      data:
                        type: array
                        description: List of all experiences' categories.
                        items:
                          type: object
                          properties:
                            id:
                              type: integer
                              description: Index of category.
                            name:
                              type: string
                              description: Name of the category.
                      message:
                        type: string
                        description: A message describing result of the action.
                    example:
                      status: success
                      data:
                      - id: 1
                        name: Painting
                      - id: 2
                        name: Caligraphy
                      message: successfully retrieve all categories
            '403':
              description: The user has not sufficient permission to access this end
                point.
              content:
                application/json:
                  schema:
                    type: object
                    properties:
                      status:
                        type: string
                        description: Result of the action
                      message:
                        type: string
                        description: A message describing result of the action.
                    example:
                      status: failed
                      message: AUTHORIZATION FAILED.
        get:
          tags:
          - Admin
          summary: Admin get all categories
          security:
          - jwt: []
          description: 'This end-point is accessible to admin and returns all registered
            categories.

            '
          responses:
            '200':
              description: List of all categories
              content:
                application/json:
                  schema:
                    type: object
                    properties:
                      status:
                        type: string
                        description: Result of the action
                      data:
                        type: array
                        description: List of all experiences' categories.
                        items:
                          type: object
                          properties:
                            id:
                              type: integer
                              description: Index of category.
                            name:
                              type: string
                              description: Name of the category.
                      message:
                        type: string
                        description: A message describing result of the action.
                    example:
                      status: success
                      data:
                      - id: 1
                        name: Painting
                      - id: 2
                        name: Caligraphy
                      message: successfully retrieve all categories
            '403':
              description: The user has not sufficient permission to access this end
                point.
              content:
                application/json:
                  schema:
                    type: object
                    properties:
                      status:
                        type: string
                        description: Result of the action
                      message:
                        type: string
                        description: A message describing result of the action.
                    example:
                      status: failed
                      message: AUTHORIZATION FAILED.
  areas:
    default:
      path_patterns:
      - ^/api(?!/(doc|v1\/checkoutCallback|v1\/auth\/refresh))
