version: '3.7'

services:
  backend:
    container_name: 'backend'
    environment:
      DATABASE_URL: "mysql://root:password@database/main?serverVersion=8&charset=utf8mb4"
      REDIS_URL: "tcp://redis"
    build: .
    ports:
      - "127.0.0.1:8000:8000"
    links:
      - database
      - redis
    depends_on:
      - database
      - redis
  database:
    image: 'mysql:latest'
    container_name: 'database'
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: main
    volumes:
      - options-db:/var/lib/mysql
    ports:
      - "3309:3306"
  redis:
    image: 'redis:latest'
    container_name: 'redis'

volumes:
  options-db: