auth.login:
    path: /api/v1/auth/login
    methods: ['POST']
auth.refresh:
    path: /api/v1/auth/refresh
    methods: ['POST']
    controller: gesdinet.jwtrefreshtoken::refresh
auth.logout:
    path: /api/v1/auth/logout
    methods: ['POST']
controllers:
    resource: ../src/Controller/
    type: attribute